sudo: required

services:
  - docker

before_install:
  - docker build -t devraj4522/docker-react-stephen-grider -f Dockerfile.dev .

script:
  - docker run devraj4522/docker-react-stephen-grider  npm run test -- -- coverage # docker run id_name npm run test